package service

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"

	"github.com/mhsanaei/3x-ui/v2/logger"
)

const (
	bbrConfigPath = "/etc/sysctl.d/99-vpn-ui-bbr.conf"
	bbrStatePath  = "/var/lib/vpn-ui/bbr-state.json"
	bbrMarker     = "# Managed by vpn-ui;"
)

var ErrBBRUnavailable = errors.New("BBR unavailable on this kernel")

type BBRStatus struct {
	Supported                  bool   `json:"supported"`
	Available                  bool   `json:"available"`
	Enabled                    bool   `json:"enabled"`
	CurrentCongestionControl   string `json:"currentCongestionControl"`
	AvailableCongestionControl string `json:"availableCongestionControl"`
	CurrentQdisc               string `json:"currentQdisc"`
	Kernel                     string `json:"kernel"`
	Persistent                 bool   `json:"persistent"`
	Managed                    bool   `json:"managed"`
	ConfigPath                 string `json:"configPath"`
}

type bbrState struct {
	CongestionControl string `json:"congestionControl"`
	DefaultQdisc      string `json:"defaultQdisc"`
}

func bbrSysctl(name string) string {
	cmd := exec.Command("sysctl", "-n", name)
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func bbrKernel() string {
	if runtime.GOOS != "linux" {
		return runtime.GOOS
	}
	out, err := exec.Command("uname", "-r").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func BBRStatusSnapshot() BBRStatus {
	s := BBRStatus{Kernel: bbrKernel(), ConfigPath: bbrConfigPath}
	if runtime.GOOS != "linux" {
		return s
	}
	s.Supported = bbrSysctl("net.ipv4.tcp_available_congestion_control") != ""
	s.AvailableCongestionControl = bbrSysctl("net.ipv4.tcp_available_congestion_control")
	s.CurrentCongestionControl = bbrSysctl("net.ipv4.tcp_congestion_control")
	s.CurrentQdisc = bbrSysctl("net.core.default_qdisc")
	s.Available = containsWord(s.AvailableCongestionControl, "bbr")
	s.Enabled = s.Available && s.CurrentCongestionControl == "bbr"
	data, err := os.ReadFile(bbrConfigPath)
	s.Managed = err == nil && strings.HasPrefix(string(data), bbrMarker)
	s.Persistent = s.Managed && strings.Contains(string(data), "net.ipv4.tcp_congestion_control=bbr")
	return s
}

func containsWord(value, want string) bool {
	for _, word := range strings.Fields(value) {
		if word == want {
			return true
		}
	}
	return false
}

func safeBBRValue(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9') && r != '.' && r != '_' && r != '-' {
			return false
		}
	}
	return true
}

func BBRAvailable() bool { return BBRStatusSnapshot().Available }

func writeBBRFile(content []byte) error {
	if err := os.MkdirAll("/var/lib/vpn-ui", 0755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp("/var/lib/vpn-ui", ".bbr-state-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name)
	if err = tmp.Chmod(0600); err == nil {
		_, err = tmp.Write(content)
	}
	if closeErr := tmp.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return err
	}
	return os.Rename(name, bbrStatePath)
}

func EnableBBR() (BBRStatus, error) {
	status := BBRStatusSnapshot()
	if runtime.GOOS != "linux" || !status.Available {
		if runtime.GOOS == "linux" {
			_ = exec.Command("modprobe", "tcp_bbr").Run()
			status = BBRStatusSnapshot()
		}
		if !status.Available {
			return status, ErrBBRUnavailable
		}
	}
	if raw, err := os.ReadFile(bbrConfigPath); err == nil && !strings.HasPrefix(string(raw), bbrMarker) {
		return status, fmt.Errorf("refusing to overwrite non-vpn-ui sysctl file %s", bbrConfigPath)
	}
	previous := bbrState{}
	if status.CurrentCongestionControl != "" {
		previous.CongestionControl = status.CurrentCongestionControl
	}
	if status.CurrentQdisc != "" {
		previous.DefaultQdisc = status.CurrentQdisc
	}
	state, _ := json.Marshal(previous)
	if err := writeBBRFile(state); err != nil {
		return status, err
	}
	conf := []byte(bbrMarker + " do not edit this file to change ownership.\nnet.core.default_qdisc=fq\nnet.ipv4.tcp_congestion_control=bbr\n")
	if err := os.WriteFile(bbrConfigPath, conf, 0644); err != nil {
		return status, err
	}
	if err := exec.Command("sysctl", "-w", "net.core.default_qdisc=fq").Run(); err != nil {
		return BBRStatusSnapshot(), err
	}
	if err := exec.Command("sysctl", "-w", "net.ipv4.tcp_congestion_control=bbr").Run(); err != nil {
		return BBRStatusSnapshot(), err
	}
	status = BBRStatusSnapshot()
	if !status.Enabled {
		return status, errors.New("BBR settings did not verify after applying")
	}
	return status, nil
}

func DisableBBR() (BBRStatus, error) {
	raw, err := os.ReadFile(bbrConfigPath)
	if err != nil {
		return BBRStatusSnapshot(), nil
	}
	if !strings.HasPrefix(string(raw), bbrMarker) {
		return BBRStatusSnapshot(), fmt.Errorf("refusing to remove non-vpn-ui sysctl file %s", bbrConfigPath)
	}
	previous := bbrState{}
	if state, readErr := os.ReadFile(bbrStatePath); readErr == nil {
		_ = json.Unmarshal(state, &previous)
	}
	if safeBBRValue(previous.DefaultQdisc) {
		_ = exec.Command("sysctl", "-w", "net.core.default_qdisc="+previous.DefaultQdisc).Run()
	}
	if safeBBRValue(previous.CongestionControl) {
		_ = exec.Command("sysctl", "-w", "net.ipv4.tcp_congestion_control="+previous.CongestionControl).Run()
	}
	if err := os.Remove(bbrConfigPath); err != nil && !os.IsNotExist(err) {
		return BBRStatusSnapshot(), err
	}
	_ = os.Remove(bbrStatePath)
	logger.Info("vpn-ui BBR configuration reverted")
	return BBRStatusSnapshot(), nil
}
